### ISSUE TITLE
Build a recommendation engine to recommend top n restaurants for a given user

### ISSUE THREAD

**Issue by ravichandrakolluri** [bdiptesh/rec_engine#1]
**Is your feature request related to a problem? Please describe.**
To enhance the user engagement on the app.

**Describe the solution you'd like**
Given a new user and his preferences, recommend top n restaurants

**Expected inputs**

Catalog:

```python
site: int
a1: int
a2: int
a3: int
a4: int
a5: int
```

User preferences:

```python
guest: int
a1: int
a2: int
a3: int
a4: int
a5: int
```
**Expected output**
```python
guest: int
site: int
match: int
score: Union[float, int]
```

**Additional context**
In case of no preferences available for an user, return `None`

**Acceptance criteria**
- [ ] Latency required: 100 ms per user

**Tasks**

- [ ] Document the approach
- [ ] Modular program with associated integration tests
